In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns # 시각화 라이브러리

In [2]:


train = pd.read_csv('./data/Train.csv')
test = pd.read_csv('./data/Test.csv')

In [5]:
train.drop('ID',axis =1 ,inplace=True)
test.drop('ID',axis =1 ,inplace=True)

In [6]:
test.drop('Gender',axis =1, inplace=True)
train.drop('Gender',axis =1, inplace=True)

In [7]:
train.isnull()

,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
0,False,False,False,False,False,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,True,False,False,False,False
4,False,False,True,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...
6994,False,False,False,False,False,False,False,False,False,False
6995,False,False,False,False,False,False,False,True,False,False
6996,False,False,True,False,False,False,False,False,False,False
6997,False,False,False,False,False,False,False,True,False,False
6998,False,False,False,False,False,False,False,True,False,False